version: 2

project_name: darght

builds:
  - id: darght
    main: .
    binary: darght
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Inject build-time metadata into the binary
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

release:
  github: {}

changelog:
  use: git
  sort: asc

snapshot: {}

# No Docker or signing configured by default
dockers: []
signs: []

# Keep brew/formula and other extensible sections empty for now
# Homebrew cask publishing (tap: sebakri/homebrew-tools)
homebrew_casks:
  - name: darght
    homepage: "https://github.com/sebakri/darght"
    description: "Theme detection CLI"
    repository:
      owner: "sebakri"
      name: "homebrew-tools"
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    directory: "Casks"
    url:
      verified: "github.com/sebakri/darght"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/darght"]
          end
    commit_author:
      name: "GitHub Actions"
      email: "actions@github.com"
