name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Build & Release via goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests (Darwin)
        env:
          GOOS: "darwin"
        run: go test ./...

      - name: Run tests (Windows)
        env:
          GOOS: "windows"
        run: go test ./...

      - name: Verify HOMEBREW_TOKEN permissions (debug)
        if: always()
        run: |
          if [ -z "${HOMEBREW_TOKEN:-}" ]; then
            echo "HOMEBREW_TOKEN is not set (secret not provided)"
            exit 1
          fi
          echo "Querying target tap repo permissions..."
          # Prefer jq if available; otherwise print a truncated raw response
          if command -v jq >/dev/null 2>&1; then
            curl -s -H "Authorization: token $HOMEBREW_TOKEN" https://api.github.com/repos/sebakri/homebrew-tools | jq '.permissions'
          else
            echo "jq not found; printing raw response (truncated)"
            curl -s -H "Authorization: token $HOMEBREW_TOKEN" https://api.github.com/repos/sebakri/homebrew-tools | sed -n '1,160p'
          fi
        env:
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
